language: php
php:
    0: 7.1
    1: 7.2
    2: 5.6
    3: 7
    5: hhvm
dist: trusty
cache:
    directories:
        - $HOME/.composer/cache
before_install:
    - 'composer self-update'
    - 'composer --version'
    - 'wget http://hiqdev.com/hidev/hidev.phar -O hidev.phar && chmod a+x hidev.phar'
    - './hidev.phar --version'
    - './hidev.phar travis/before-install'
matrix:
    allow_failures:
        -
            php: hhvm
sudo: false
install:
    - './hidev.phar travis/install'
script:
    - './hidev.phar travis/script'
after_script:
    - './hidev.phar travis/after-script'
